[package]
name = "rtiow"
version = "0.1.0"
authors = ["Elliott Barcikowski ebarcikowski@gmail.com"]

[lib]
name = "rtiow"
create-type = ["cdynlib"]
bench = false

[[bin]]
name = "ppm"

[[bin]]
name = "sphere"




# file = "src/bin/ppm.rs"